### ISSUE TITLE
can't pull all the history

### ISSUE THREAD

**Issue by 40-02** [KyleAMathews/facebook-export#17]
Can't pull all the history

in the end it gives me error:

```
fetched undefined posts. The oldest post fetched was last updated: Thursday, August 4th 2016, 4:45:36 pm
/usr/local/lib/node_modules/facebook-export/lib/fetch_posts.coffee:40
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
                               ^
TypeError: Cannot read property 'length' of undefined
    at Request._callback (/usr/local/lib/node_modules/facebook-export/lib/fetch_posts.coffee:40:32)
    at Request.self.callback (/usr/local/lib/node_modules/facebook-export/node_modules/request/request.js:123:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/facebook-export/node_modules/request/request.js:893:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/facebook-export/node_modules/request/request.js:844:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by BlurrySasquatch** [comment]
I am encountering the same thing
