### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by molinto** [KyleAMathews/facebook-export#6]
$ facebook-export -a APIKEY -g GROUPID -d

fetched 9 posts. The oldest post fetched was last updated: Monday, March 2nd 2015, 4:37:49 pm
fetched 9 posts. The oldest post fetched was last updated: Monday, March 2nd 2015, 1:18:40 pm
fetched 9 posts. The oldest post fetched was last updated: Sunday, March 1st 2015, 9:08:10 pm
fetched undefined posts. The oldest post fetched was last updated: Wednesday, March 4th 2015, 5:20:30 pm

TypeError: Cannot read property 'length' of undefined
    at Request._callback (/usr/lib/node_modules/facebook-export/lib/fetch_posts.coffee:40:32)
    at Request.self.callback (/usr/lib/node_modules/facebook-export/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/facebook-export/node_modules/request/request.js:893:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/facebook-export/node_modules/request/request.js:844:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by KyleAMathews** [comment]
Does this happen every time you try to fetch posts? With every group?

**Comment by molinto** [comment]
Seems to be only on a group I'm admin of: id 26106060048

Great project btw :)

**Comment by bengu** [comment]
Sometimes FB returns this evil answer. It destroys most implementations

{
  "error": {
    "message": "An unknown error has occurred.",
    "type": "OAuthException",
    "code": 1,
    "fbtrace_id": "q9JAVCCyyxT"
  }
}

**Comment by bengu** [comment]
These fields seems safe to use:
?fields=from,to,message,created_time,updated_time,likes,comments

The others often create unknown errors.
